I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    image boat = im.FactorScale("images/boat.png")
  File "game/script.rpy", line 28, in <module>
    image boat = im.FactorScale("images/boat.png")
TypeError: __init__() takes at least 3 arguments (2 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script
    image boat = im.FactorScale("images/boat.png")
  File "/Applications/renpy-6.99.6-sdk/renpy/ast.py", line 888, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Applications/renpy-6.99.6-sdk/renpy/python.py", line 1472, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 28, in <module>
    image boat = im.FactorScale("images/boat.png")
TypeError: __init__() takes at least 3 arguments (2 given)

Darwin-14.5.0-x86_64-i386-64bit
Ren'Py 6.99.6.739
TESL 0.0
