I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/rootInferno.rpy", line 32, in script
    scene bg night ocean with blink
  File "game/rootInferno.rpy", line 32, in <module>
    scene bg night ocean with blink
NameError: name 'blink' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/rootInferno.rpy", line 32, in script
    scene bg night ocean with blink
  File "/Applications/renpy-6.99.6-sdk/renpy/ast.py", line 1246, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/Applications/renpy-6.99.6-sdk/renpy/python.py", line 1477, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-6.99.6-sdk/renpy/python.py", line 1472, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/rootInferno.rpy", line 32, in <module>
    scene bg night ocean with blink
NameError: name 'blink' is not defined

Darwin-14.5.0-x86_64-i386-64bit
Ren'Py 6.99.6.739
TESL 0.0
